# Generated by Django 4.1.3 on 2023-04-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyurtma',
            name='miqdori',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
